R CMD INSTALL --build FLCore*.tar.gz
R CMD INSTALL --build ggplotFL*.tar.gz
R CMD INSTALL --build FLa4a*.tar.gz
R CMD INSTALL --build FLBRP*.tar.gz
R CMD INSTALL --build FLFishery*.tar.gz
R CMD INSTALL --build FLasher*.tar.gz
R CMD INSTALL --build FLAssess*.tar.gz
R CMD INSTALL --build FLXSA*.tar.gz
R CMD INSTALL --build FLSAM*.tar.gz
R CMD INSTALL --build FLash*.tar.gz
R CMD INSTALL --build mse*.tar.gz
R CMD INSTALL --build mseviz*.tar.gz
R CMD INSTALL --build bbm*.tar.gz
R CMD INSTALL --build FLife*.tar.gz
R CMD INSTALL --build kobe*.tar.gz
R CMD INSTALL --build diags*.tar.gz
R CMD INSTALL --build mpb*.tar.gz
R CMD INSTALL --build FLFleet*.tar.gz
R CMD INSTALL --build FLBEIA*.tar.gz
R CMD INSTALL --build ss3om*.tar.gz
R CMD INSTALL --build mydas*.tar.gz
R CMD INSTALL --build mpb*.tar.gz
